#!/usr/bin/env python3
"""Base-10 orbit classification diagnostics for the prime/operator lane.

This tool classifies primes by the multiplicative orbit of 10 modulo p and
verifies the finite Fourier cancellation law:

    sum_{h in <10>} chi(h) = 0 unless chi is trivial on <10>.

It is a finite arithmetic diagnostic. It does not prove Artin's conjecture,
RH, GRH, or any unconditional variance bound.
"""

from __future__ import annotations

import cmath
import math
from dataclasses import dataclass
from typing import Dict, Iterable, List, Tuple


@dataclass(frozen=True)
class OrbitClassification:
    prime: int
    category: str
    period: int | None
    orbit: Tuple[int, ...]
    nontrivial_characters: int
    cancelling_nontrivial_characters: int
    noncancelling_nontrivial_characters: int


def is_prime(n: int) -> bool:
    if n < 2:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    d = 3
    while d * d <= n:
        if n % d == 0:
            return False
        d += 2
    return True


def primes_up_to(limit: int) -> List[int]:
    return [n for n in range(2, limit + 1) if is_prime(n)]


def multiplicative_order_mod_prime(base: int, prime: int) -> int | None:
    if math.gcd(base, prime) != 1:
        return None
    value = 1
    for order in range(1, prime):
        value = (value * base) % prime
        if value == 1:
            return order
    raise RuntimeError(f"order not found for base={base} mod p={prime}")


def orbit_mod_prime(base: int, prime: int) -> Tuple[int, ...]:
    order = multiplicative_order_mod_prime(base, prime)
    if order is None:
        return tuple()
    value = 1
    values: List[int] = []
    for _ in range(order):
        value = (value * base) % prime
        values.append(value)
    return tuple(values)


def primitive_root_primes(limit: int, base: int = 10) -> List[int]:
    return [p for p in primes_up_to(limit) if multiplicative_order_mod_prime(base, p) == p - 1]


def character_value_mod_prime(prime: int, generator: int, exponent: int, residue: int) -> complex:
    if residue % prime == 0:
        return 0j
    value = 1
    for k in range(prime - 1):
        if value == residue % prime:
            return cmath.exp(2j * math.pi * exponent * k / (prime - 1))
        value = (value * generator) % prime
    raise ValueError(f"residue {residue} not generated by {generator} mod {prime}")


def primitive_generator_mod_prime(prime: int) -> int:
    for candidate in range(2, prime):
        if multiplicative_order_mod_prime(candidate, prime) == prime - 1:
            return candidate
    raise RuntimeError(f"no primitive generator found mod {prime}")


def orbit_character_sum(prime: int, exponent: int, base: int = 10) -> complex:
    order = multiplicative_order_mod_prime(base, prime)
    if order is None:
        return 0j
    generator = primitive_generator_mod_prime(prime)
    return sum(character_value_mod_prime(prime, generator, exponent, residue) for residue in orbit_mod_prime(base, prime))


def classify_prime(prime: int, base: int = 10) -> OrbitClassification:
    if math.gcd(base, prime) != 1:
        return OrbitClassification(
            prime=prime,
            category="terminating",
            period=None,
            orbit=tuple(),
            nontrivial_characters=0,
            cancelling_nontrivial_characters=0,
            noncancelling_nontrivial_characters=0,
        )

    order = multiplicative_order_mod_prime(base, prime)
    assert order is not None
    orbit = orbit_mod_prime(base, prime)

    cancelling = 0
    noncancelling = 0
    for exponent in range(1, prime - 1):
        total = orbit_character_sum(prime, exponent, base)
        if abs(total) < 1e-9:
            cancelling += 1
        else:
            noncancelling += 1

    if order == 1:
        category = "degenerate"
    elif order == prime - 1:
        category = "full"
    else:
        category = "partial"

    return OrbitClassification(
        prime=prime,
        category=category,
        period=order,
        orbit=orbit,
        nontrivial_characters=prime - 2,
        cancelling_nontrivial_characters=cancelling,
        noncancelling_nontrivial_characters=noncancelling,
    )


def classify_primes(primes: Iterable[int], base: int = 10) -> Tuple[OrbitClassification, ...]:
    return tuple(classify_prime(p, base) for p in primes)


def run_checks() -> Tuple[OrbitClassification, ...]:
    rows = classify_primes((2, 3, 5, 7, 11, 19, 23, 29), 10)
    by_prime = {row.prime: row for row in rows}

    if by_prime[2].category != "terminating" or by_prime[5].category != "terminating":
        raise AssertionError("2 and 5 must terminate in base 10")
    if by_prime[3].category != "degenerate" or by_prime[3].period != 1:
        raise AssertionError("3 must be the prime degenerate base-10 orbit")
    if by_prime[7].category != "full" or by_prime[7].period != 6:
        raise AssertionError("7 must be full orbit for base 10")
    if by_prime[11].category != "partial" or by_prime[11].period != 2:
        raise AssertionError("11 must be partial orbit of length 2")
    if by_prime[19].category != "full" or by_prime[19].period != 18:
        raise AssertionError("19 must be full orbit for base 10")

    if by_prime[7].cancelling_nontrivial_characters != 5:
        raise AssertionError("all five nontrivial mod-7 characters should cancel on full orbit")
    if by_prime[11].cancelling_nontrivial_characters != 5 or by_prime[11].noncancelling_nontrivial_characters != 4:
        raise AssertionError("mod-11 partial orbit should cancel exactly five nontrivial characters")

    expected_artin_prefix = [7, 17, 19, 23, 29, 47, 59, 61, 97]
    found_prefix = primitive_root_primes(100, 10)
    if found_prefix[: len(expected_artin_prefix)] != expected_artin_prefix:
        raise AssertionError(found_prefix)

    return rows


def main() -> None:
    print("Base-10 orbit classification")
    for row in run_checks():
        print(
            f"p={row.prime} category={row.category} period={row.period} "
            f"orbit={row.orbit} nontrivial={row.nontrivial_characters} "
            f"cancelling={row.cancelling_nontrivial_characters} "
            f"noncancelling={row.noncancelling_nontrivial_characters}"
        )
    print(f"base-10 primitive-root primes <=100: {primitive_root_primes(100, 10)}")


if __name__ == "__main__":
    main()
